-- 테이블 설정
CREATE TABLE `AC_MM_CONTACT` (
  `CONTACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CHANNEL_KEY` varchar(512) COLLATE utf8_bin NOT NULL,
  `KEY` varchar(30) COLLATE utf8_bin NOT NULL,
  `ANI` varchar(20) COLLATE utf8_bin NOT NULL,
  `INSERT_BY` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `UPDATE_BY` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `INSERT_DT` datetime NOT NULL,
  `UPDATE_DT` datetime NOT NULL,
  `REMOVE_DT` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- PK 설정
ALTER TABLE AAPADM.AC_MM_SCHEDULE_STAC_MM_CONTACTATUS ADD PRIMARY KEY (CONTACT_ID);

-- 코멘트 설정
ALTER TABLE AAPADM.AC_MM_CONTACT COMMENT = '고객 접근 정보';
ALTER TABLE AAPADM.AC_MM_CONTACT MODIFY `CHANNEL_KEY` varchar(512) COLLATE utf8_bin NOT NULL COMMENT '채널 키';
ALTER TABLE AAPADM.AC_MM_CONTACT MODIFY `KEY` varchar(30) COLLATE utf8_bin NOT NULL COMMENT '컨택 키';
ALTER TABLE AAPADM.AC_MM_CONTACT MODIFY `ANI` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '전화번호';

-- 권한 설정
GRANT DELETE, INSERT, SELECT, UPDATE ON AAPADM.AC_MM_CONTACT TO AAPCON;

-- 설정 적용
FLUSH PRIVILEGES;