-- 테이블 설정
CREATE TABLE `AC_MM_SCHEDULE_LOCK` (
  `SCHEDULE_LOCK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCHEDULE_NM` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '스케쥴명 (작업 종류)',
  `NODE_NM` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '노드명 (작업 수행 서버명)',
  `DATE_CRITERIA` date NOT NULL COMMENT '시도 기준 일자',
  `LOCK_UNTIL` datetime NOT NULL COMMENT 'Lock 유효 시간',
  `LOCKED_AT` varchar(20) COLLATE utf8_bin NOT NULL COMMENT 'Lock 설정 시간 (HHmmssSSS)',
  `REMOVE_DT` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- PK 설정
ALTER TABLE AAPADM.AC_MM_SCHEDULE_LOCK ADD PRIMARY KEY (SCHEDULE_LOCK_ID);

-- 코멘트 설정
ALTER TABLE AAPADM.AC_MM_SCHEDULE_LOCK COMMENT = '통합키 발급 이력';
ALTER TABLE AAPADM.AC_MM_SCHEDULE_LOCK MODIFY `SCHEDULE_NM` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '스케쥴명 (작업 종류)';
ALTER TABLE AAPADM.AC_MM_SCHEDULE_LOCK MODIFY `NODE_NM` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '노드명 (작업 수행 서버명)';
ALTER TABLE AAPADM.AC_MM_SCHEDULE_LOCK MODIFY `DATE_CRITERIA` date NOT NULL COMMENT '시도 기준 일자';
ALTER TABLE AAPADM.AC_MM_SCHEDULE_LOCK MODIFY `LOCK_UNTIL` datetime NOT NULL COMMENT 'Lock 유효 시간';
ALTER TABLE AAPADM.AC_MM_SCHEDULE_LOCK MODIFY `LOCKED_AT` varchar(20) COLLATE utf8_bin NOT NULL COMMENT 'Lock 설정 시간 (HHmmssSSS)';

-- 권한 설정
GRANT DELETE, INSERT, SELECT, UPDATE ON AAPADM.AC_MM_SCHEDULE_LOCK TO AAPCON;

-- 설정 적용
FLUSH PRIVILEGES;