-- 테이블 설정
CREATE TABLE `AC_MM_CONTACT_ATTRIBUTE` (
  `CONTACT_ATTRIBUTE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTACT_ID` int(11) NOT NULL,
  `NAME` varchar(50) COLLATE utf8_bin NOT NULL,
  `VALUE` varchar(200) COLLATE utf8_bin NOT NULL,
  `INSERT_BY` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `UPDATE_BY` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `INSERT_DT` datetime NOT NULL,
  `UPDATE_DT` datetime NOT NULL,
  `REMOVE_DT` datetime DEFAULT NULL,
  KEY `CONTACT_ID` (`CONTACT_ID`),
  CONSTRAINT `AC_MM_CONTACT_ATTRIBUTE_ibfk_1` FOREIGN KEY (`CONTACT_ID`) REFERENCES `AC_MM_CONTACT` (`CONTACT_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- PK 설정
ALTER TABLE AAPADM.AC_MM_CONTACT_ATTRIBUTE ADD PRIMARY KEY (CONTACT_ATTRIBUTE_ID);

-- 코멘트 설정
ALTER TABLE AAPADM.AC_MM_CONTACT_ATTRIBUTE COMMENT = '고객 접근 정보 속성';
ALTER TABLE AAPADM.AC_MM_CONTACT_ATTRIBUTE MODIFY `CONTACT_ID` int(11) NOT NULL COMMENT '컨택 식별자';
ALTER TABLE AAPADM.AC_MM_CONTACT_ATTRIBUTE MODIFY `NAME` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '속성명';
ALTER TABLE AAPADM.AC_MM_CONTACT_ATTRIBUTE MODIFY `VALUE` varchar(200) COLLATE utf8_bin NOT NULL COMMENT '속성값';

-- 권한 설정
GRANT DELETE, INSERT, SELECT, UPDATE ON AAPADM.AC_MM_CONTACT_ATTRIBUTE TO AAPCON;

-- 설정 적용
FLUSH PRIVILEGES;