-- 테이블 설정
CREATE TABLE `AC_MM_PRI_BIZ_INFO` (
  `CONF_TYPE` varchar(10) COLLATE utf8_bin NOT NULL COMMENT '우선순위 노출 타입',
  `PRI_GROUP_CD` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '필요서류 그룹 코드',
  `PRI_STEP_CD` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '코드',
  `PRI_STEP_NM` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '이름',
  `PRI_STEP_OD` int(11) NOT NULL COMMENT '순서',
  `UPDATE_USER` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '업데이트 유저',
  `UPDATE_TIME` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '업데이트 날짜'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- PK 설정

-- 코멘트 설정
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO COMMENT = '필요서류 우선순위';
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO MODIFY `CONF_TYPE` varchar(10) COLLATE utf8_bin NOT NULL COMMENT '우선순위 노출 타입';
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO MODIFY `PRI_GROUP_CD` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '필요서류 그룹 코드';
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO MODIFY `PRI_STEP_CD` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '코드';
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO MODIFY `PRI_STEP_NM` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '이름';
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO MODIFY `PRI_STEP_OD` int(11) NOT NULL COMMENT '순서';
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO MODIFY `UPDATE_USER` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '업데이트 유저';
ALTER TABLE AAPADM.AC_MM_PRI_BIZ_INFO MODIFY `UPDATE_TIME` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '업데이트 날짜';

-- 권한 설정
GRANT DELETE, INSERT, SELECT, UPDATE ON AAPADM.AC_MM_PRI_BIZ_INFO TO AAPCON;

-- 설정 적용
FLUSH PRIVILEGES;