-- 테이블 설정
CREATE TABLE `AC_MM_BIZ_INFO` (
  `NCSY_DCMT_DV_CD` varchar(32) COLLATE utf8_bin NOT NULL,
  `BIZ_SEQ_NO` int(11) DEFAULT NULL,
  `STEP_1_CD` varchar(32) COLLATE utf8_bin NOT NULL,
  `STEP_1_NM` varchar(255) COLLATE utf8_bin NOT NULL,
  `STEP_2_CD` varchar(32) COLLATE utf8_bin NOT NULL,
  `STEP_2_NM` varchar(255) COLLATE utf8_bin NOT NULL,
  `STEP_3_CD` varchar(32) COLLATE utf8_bin NOT NULL,
  `STEP_3_NM` varchar(255) COLLATE utf8_bin NOT NULL,
  `STEP_4_CD` varchar(32) COLLATE utf8_bin NOT NULL,
  `STEP_4_NM` varchar(255) COLLATE utf8_bin NOT NULL,
  `STEP_5_CD` varchar(32) COLLATE utf8_bin NOT NULL,
  `STEP_5_NM` varchar(255) COLLATE utf8_bin NOT NULL,
  `STEP_6_CD` varchar(32) COLLATE utf8_bin NOT NULL,
  `STEP_6_NM` varchar(255) COLLATE utf8_bin NOT NULL,
  `NCSY_DCMTS` text COLLATE utf8_bin NOT NULL,
  `GUD_SNTC_CTTS_ALL` text COLLATE utf8_bin NOT NULL,
  `GUD_SNTC_CTTS_N` text COLLATE utf8_bin NOT NULL,
  `ADD_DCMT_CTT` text COLLATE utf8_bin NOT NULL,
  `NCSY_DCMT_GUD_CTT` text COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- PK 설정

-- 코멘트 설정
ALTER TABLE AAPADM.AC_MM_BIZ_INFO COMMENT = '통합키 발급 이력';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY NCSY_DCMT_DV_CD varchar(32) COLLATE utf8_bin NOT NULL COMMENT '그룹코드123';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `BIZ_SEQ_NO` int(11) DEFAULT NULL COMMENT '순서';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_1_CD` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '1.코드';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_1_NM` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '1.이름';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_2_CD` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '2.코드';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_2_NM` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '2.이름';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_3_CD` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '3.코드';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_3_NM` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '3.이름';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_4_CD` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '4.코드';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_4_NM` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '4.이름';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_5_CD` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '5.코드';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_5_NM` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '5.이름';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_6_CD` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '6.코드';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `STEP_6_NM` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '6.이름';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `NCSY_DCMTS` text COLLATE utf8_bin NOT NULL COMMENT '서류목록';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `GUD_SNTC_CTTS_ALL` text COLLATE utf8_bin NOT NULL COMMENT '안내 서류 전체';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `GUD_SNTC_CTTS_N` text COLLATE utf8_bin NOT NULL COMMENT '안내 서류 일부(빨간글씨 제외)';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `ADD_DCMT_CTT` text COLLATE utf8_bin NOT NULL COMMENT '추가 서류';
ALTER TABLE AAPADM.AC_MM_BIZ_INFO MODIFY `NCSY_DCMT_GUD_CTT` text COLLATE utf8_bin NOT NULL COMMENT '수수료 안내';

-- 권한 설정
GRANT DELETE, INSERT, SELECT, UPDATE ON AAPADM.AC_MM_BIZ_INFO TO AAPCON;

-- 설정 적용
FLUSH PRIVILEGES;