-- 테이블 설정
CREATE TABLE `AC_MM_CONTACT_SESSION` (
  `CONTACT_SESSION_ID` int(11) NOT NULL,
  `CONTACT_ID` int(11) NOT NULL COMMENT '컨택 식별자',
  `REFRESH_TOKEN` varchar(300) COLLATE utf8_bin NOT NULL,
  `EXPIRE_DT` datetime NOT NULL,
  `INSERT_BY` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `UPDATE_BY` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `INSERT_DT` datetime NOT NULL,
  `UPDATE_DT` datetime NOT NULL,
  `REMOVE_DT` datetime DEFAULT NULL,
  KEY `CONTACT_ID` (`CONTACT_ID`),
  CONSTRAINT `AC_MM_CONTACT_SESSION_ibfk_1` FOREIGN KEY (`CONTACT_ID`) REFERENCES `AC_MM_CONTACT` (`CONTACT_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- PK 설정
ALTER TABLE AAPADM.AC_MM_CONTACT_SESSION ADD PRIMARY KEY (CONTACT_SESSION_ID);

-- 코멘트 설정
ALTER TABLE AAPADM.AC_MM_CONTACT_SESSION COMMENT = '고객 접근 세션 정보';
ALTER TABLE AAPADM.AC_MM_CONTACT_SESSION MODIFY `CONTACT_ID` int(11) NOT NULL COMMENT '컨택 식별자';
ALTER TABLE AAPADM.AC_MM_CONTACT_SESSION MODIFY `REFRESH_TOKEN` varchar(300) COLLATE utf8_bin NOT NULL COMMENT 'Refresh Token (Thru)';
ALTER TABLE AAPADM.AC_MM_CONTACT_SESSION MODIFY `EXPIRE_DT` datetime NOT NULL COMMENT '만료 시간';

-- 권한 설정
GRANT DELETE, INSERT, SELECT, UPDATE ON AAPADM.AC_MM_CONTACT_SESSION TO AAPCON;

-- 설정 적용
FLUSH PRIVILEGES;